### ISSUE TITLE
CVP not executing entrypoint.sh

### ISSUE THREAD

**Issue by romecode** [networkop/docker-topo#23]
I used cvp-in-docker build commands; if I run the container from bash all seems well. However, using the docker-topo CVP declarations in endpoints, once instantiated, the entrypoint script is ignored and the cvp domain is never built. 

Any ideas?

**Comment by networkop** [comment]
try following this tutorial instead 
https://github.com/networkop/cvp-in-docker

**Comment by romecode** [comment]
Hey thanks,

That works perfect from bash.

This is the output of the failing CVP(Device) class that spins up a container for CVP:
CVP VM does not exist yet
Generating answer CDROM
Building ISO for node1 cvp: /cvp//node1-cvp.iso
Generating libvirt XML
Traceback (most recent call last):
  File "/cvp/generateXmlForKvm.py", line 249, in <module>
    main()
  File "/cvp/generateXmlForKvm.py", line 239, in main
    xml.setRam( ramMb=args.memory )
  File "/cvp/generateXmlForKvm.py", line 98, in setRam
    if int( ramMb ) < MIN_RAM_MB:
ValueError: invalid literal for int() with base 10: '192.168.100.254'
Starting CVP VM
error: Failed to open file 'result.xml': No such file or directory

error: failed to get domain 'cvp'
error: Domain not found: no domain with matching name 'cvp'

Setting iptables rules
All tasks completed. Entering sleeping loop...

so it's actually running entrypoint but failing.

**Comment by networkop** [comment]
looks like you're passing the wrong arguments to it? are you building it with docker-topo? and if yes, do you try to pass CVP IP as well? try dropping that IP and see if it makes a difference

**Comment by romecode** [comment]
Thanks for the help, yeah, that's what's breaking it. I assumed an image built with cvp-in-docker was compatible with docker-topo.
