### ISSUE TITLE
trunk between cEOS instances not working

### ISSUE THREAD

**Issue by hansbogert** [networkop/docker-topo#29]
I'm trying to get a simple topology to work

1. Two cEOS connected to each other with a trunk
2. Each has a host connected with access port 100

I expect them to be able to communicate

What I see, when using Wireshark on the connection between the cEOSs is ARP requests between the hosts, which are correctly tagged with vlan 100.

See attached tar
[twoq.tar.gz](https://github.com/networkop/docker-topo/files/3490067/twoq.tar.gz)

**Comment by networkop** [comment]
There's a known issue with cEOS running on stock (non-Arista) linux kernels where tagged packets get their dot1q header stripped before they reach the forwarding agent. Unfortunately, there's no fix for that issue and the only workaround is to use containerized vEOS.

**Comment by hansbogert** [comment]
> linux kernels where tagged packets get their dot1q header stripped before they reach the forwarding agen

Is that on the receiving side? Because I can verify that the tags are correct inside the packets in the trunk between two cEOS instances.

**Comment by hansbogert** [comment]
Also, is "containerized vEOS" an actual product? Or do you mean something as running vEOS in, for example, QEMU, which is run via Docker?

**Comment by networkop** [comment]
yeah, containerized vEOS is simply a vEOS-lab inside docker. There's a description of how to build a vEOS docker image here https://github.com/networkop/docker-topo/tree/master/topo-extra-files/veos

**Comment by networkop** [comment]
let me double-check about the trunk tags. i don't remember exactly where it gets stripped

**Comment by networkop** [comment]
i couldn't find where it gets dropped again, but it's definitely on the receiving side. the physical interface receives a tagged frame but by the time the packet reaches Etba (forwarding agent), it's already gone. I think you should be able to see that in Etba debug trace. I've logged this as a bug a year ago and there's still no eta today, so very low on dev's priority list.
