### ISSUE TITLE
Acces to docker-top device's interfaces from localhost

### ISSUE THREAD

**Issue by AJNOURI** [networkop/docker-topo#31]
Hey,
To simulate access to switch's management interfaces through a management network (OOB), is it possible to configure the switches to connect to a local bridge, so we could access their mngt interfaces from the host?

I already have CVP latest version running on my host and I would like it to manage docker-topo devices.
Thanks.

**Comment by networkop** [comment]
yes, it is possible. you need to set driver for the first link to "bridge" and connect all devices (including CVP) to this link. you won't see the IP on the management interface, but you can do "docker inspect SWITCH_NAME" to see what IP was given to the switch by dhcp and import it from CVP.
