### ISSUE TITLE
SNMP port mapping

### ISSUE THREAD

**Issue by pshri** [networkop/docker-topo#9]
Thanks for providing cEOS-lab docker image and topology tool.  Please consider adding support for publishing snmp port.

**Comment by networkop** [comment]
ok, will push a change in a few days

**Comment by pshri** [comment]
Thanks. I ended up modifying the tool. See attached.

PUBLISH_SNMP publishes the snmp port for each ceos device.
PUBLISH_SNMP_IP publishes snmp port to different ip addresses. requires snmp_ips array.
[docker-topo.txt](https://github.com/networkop/arista-ceos-topo/files/2142642/docker-topo.txt)

**Comment by networkop** [comment]
I've added a generic mechanism to publish any number of ports. check out my latest commit.

**Comment by pshri** [comment]
Having trouble with PUBLISH_BASE: [443/tcp:[127.0.0.1,4343]]
DEBUG:__main__:PUBLISH_BASE is [{'443/tcp': ['127.0.0.1', 4343]}] of type <class 'list'>
Traceback (most recent call last):
  File "/usr/local/bin/docker-topo", line 628, in <module>
    main()
  File "/usr/local/bin/docker-topo", line 574, in main
    internal,e   = ports.split(":")
AttributeError: 'dict' object has no attribute 'split'

I had modified the tool to publish the ports as below
DEBUG:__main__:Publishing 2node_dev1's port 161 to 127.0.0.1:50000
DEBUG:__main__:Publishing 2node_dev2's port 161 to 127.0.0.2:50000

VERSION: 2
CEOS_IMAGE: ceosimage:latest
#PUBLISH_BASE: [443/tcp:[127.0.0.1,4343]]
#PUBLISH_BASE: [123/tcp:456]
driver: veth
links:
        - endpoints:
            - "dev1:eth1"
            - "dev2:eth2"
        - endpoints: ["dev1:eth2", "dev2:eth1"]

PUBLISH_SNMP_IP: 50000
snmp_ips:
  - 127.0.0.1
  - 127.0.0.2

**Comment by networkop** [comment]
try wrapping each element of a list in quotes in order for it to be parsed as string, similar to:
PUBLISH_BASE: ["443/tcp:[127.0.0.1,4343]"]
I'll try to do more testing and update documentation over the weekend

**Comment by networkop** [comment]
issue resolved in commit https://github.com/networkop/arista-ceos-topo/commit/43d1a679ebbd9588d2f0c2b89fe27f2cf142a46e
Please see README and https://github.com/networkop/arista-ceos-topo/blob/master/topo-extra-files/examples/v1-legacy/mport.yml
